[[authors]]
email = "chuasega1991@gmail.com"
name.default = "James Choi"
name.zh-CN = "阿嘉"

[[wallpapers]]
title.default = "Theatre"
title.zh-CN = "剧院"
license = "CC-BY-4.0"
id = "Theatre"
path = "Theatre.jpg"

[[wallpapers]]
title.default = "Back of Bazaar"
title.zh-CN = "动静"
license = "CC-BY-4.0"
id = "Back_of_Bazaar"
path = "Back_of_Bazaar.jpg"
