[[authors]]
email = "cyanoxygen2725@gmail.com"
name.default = "LaoDuDu"
name.zh-CN = "老嘟嘟"

[[wallpapers]]
title.default = "Journey's Gateway"
title.zh-CN = "天山之谷"
license = "CC-BY-SA-4.0"
id = "Journeys_Gateway"
path = "Journeys_Gateway.png"
