[[authors]]
email = "yangziyue1224@live.com"
name.default = "YzyParry"

[[wallpapers]]
title.default = "Morry Ray Upon Meili"
title.zh-CN = "梅里雪山日出"
license = "CC-BY-NC-4.0"
id = "Morrow_Ray_Upon_Meili"
path = "Morrow_Ray_Upon_Meili.jpg"
