[[authors]]
email = "reivzy@gmail.com"
name.default = "Yu Changyuan"
name.zh-CN = "喻昌远"

[[wallpapers]]
title.default = "Mount Fuji I"
title.zh-CN = "富士山 I"
license = "CC-BY-NC-SA-4.0"
id = "Mount_Fuji_I"
path = "Mount_Fuji_I.jpg"

[[wallpapers]]
title.default = "Mount Fuji III"
title.zh-CN = "富士山 III"
license = "CC-BY-NC-SA-4.0"
id = "Mount_Fuji_III"
path = "Mount_Fuji_III.jpg"

[[wallpapers]]
title.default = "Pamukkale"
title.zh-CN = "棉花堡"
license = "CC-BY-NC-SA-4.0"
id = "Pamukkale"
path = "Pamukkale.jpg"

[[wallpapers]]
title.default = "Qilian Mountain"
title.zh-CN = "祁连山"
license = "CC-BY-NC-SA-4.0"
id = "Qilian_Mountain"
path = "Qilian_Mountain.jpg"

[[wallpapers]]
title.default = "Rapeseed Field I"
title.zh-CN = "油菜花田 I"
license = "CC-BY-NC-SA-4.0"
id = "Rapeseed_Field_I"
path = "Rapeseed_Field_I.jpg"

[[wallpapers]]
title.default = "Rapeseed Field III"
title.zh-CN = "油菜花田 III"
license = "CC-BY-NC-SA-4.0"
id = "Rapeseed_Field_III"
path = "Rapeseed_Field_III.jpg"
