[[authors]]
email = "reimu-harmonica@pku.edu.cn"
name.default = "Hakurei Reimu"

[[wallpapers]]
title.default = "Cupboard"
title.zh-CN = "橱柜"
license = "CC-BY-SA-4.0"
id = "Cupboard"
path = "Cupboard.jpg"
